token = '423184951:AAGpXg31f2YlbZ76Rgi0vO8X5xWETP-L26M'
help_txt=('доступныее действия simple_mod:\n'
       '+, -\n'
       '* or ×, / or ÷\n' '% or mod, // or div\n'
       'log(x,[base](const=e)), log2(x), log10(x)\n'
       'const: e, pi\n'
       'cos(x), sin(x), tan(x)\n'
       'asin(x), acos(x), atan(x)\n'
       'degrees(X) - конвертирует радианы в градусы.\n'
       'radians(X) - конвертирует градусы в радианы.\n'
        'facrotials(x) or x!\n'
          'hard_mod:\n'
          'limin(f, variable, point)-предел\n'
          'diff(f, var, n)-производная var-переменная,n-порядок')